FROM tarantool/tarantool:2.8

ARG APP_RATE_LIMIT_TOTAL
ARG APP_RATE_LIMIT_TIME_FRAME_SEC
ENV APP_RATE_LIMIT_TOTAL=${APP_RATE_LIMIT_TOTAL}
ENV APP_RATE_LIMIT_TIME_FRAME_SEC=${APP_RATE_LIMIT_TIME_FRAME_SEC}

COPY src/ /opt/tarantool

CMD ["tarantool", "/opt/tarantool/app.lua"]
EXPOSE 8080